import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { CITY_IDS, CITY_NAMES, CITY_PROFILES, CITY_SEARCH_ALIASES, CITY_TIER_LABELS, FEATURED_CITY_IDS, type CityId, type PriceRecord } from '../../packages/core/src/index.ts'

const root = resolve(import.meta.dirname, '../..')
const dataRoot = resolve(root, 'apps/web/public/data')
const output = resolve(root, 'apps/miniprogram/data/snapshot.js')
const manifest = JSON.parse(await readFile(resolve(dataRoot, 'manifest.json'), 'utf8'))
const monthLimit = 120
const months = Array.from({ length: monthLimit }, (_, offset) => {
  const date = new Date(`${manifest.dataset_as_of}-01T00:00:00Z`)
  date.setUTCMonth(date.getUTCMonth() - (monthLimit - 1 - offset))
  return date.toISOString().slice(0, 7)
})
const allowedMonths = new Set(months)
const releaseDates: Record<string, string> = {}
const bandCodes = { all: 'a', le90: 's', '90_144': 'm', gt144: 'l' } as const
const series: Record<string, Record<string, Array<number | null>>> = {}

for (const cityId of CITY_IDS) {
  const relative = manifest.city_data_url_template.replace('{city_id}', cityId).replace(/^\/data\//, '')
  const cityData = JSON.parse(await readFile(resolve(dataRoot, relative), 'utf8')) as { records: PriceRecord[] }
  if (cityId === CITY_IDS[0]) {
    for (const record of cityData.records) if (allowedMonths.has(record.stat_month)) releaseDates[record.stat_month] = record.release_date
  }
  const grouped: typeof series[string] = {}
  for (const record of cityData.records.filter((item) => allowedMonths.has(item.stat_month))) {
    const key = `${record.property_type === 'new' ? 'n' : 'r'}_${bandCodes[record.size_band]}`
    ;(grouped[key] ??= []).push(record.mom_index, record.yoy_index, record.mom_change, record.yoy_change)
  }
  for (const values of Object.values(grouped)) {
    if (values.length !== monthLimit * 4) throw new Error(`${cityId}: expected ${monthLimit * 4} values, received ${values.length}`)
  }
  if (Object.keys(grouped).length !== 8) throw new Error(`${cityId}: expected 8 series`)
  series[cityId] = grouped
}

const cityMap = Object.fromEntries(CITY_IDS.map((id: CityId) => [id, {
  name: CITY_NAMES[id],
  search: `${CITY_NAMES[id]} ${id} ${CITY_SEARCH_ALIASES[id]}`.toLowerCase(),
  province: CITY_PROFILES[id].province,
  tier: CITY_PROFILES[id].tier,
  tierLabel: CITY_TIER_LABELS[CITY_PROFILES[id].tier],
}]))
const snapshot = {
  schemaVersion: manifest.schema_version,
  datasetVersion: manifest.dataset_version,
  datasetAsOf: manifest.dataset_as_of,
  releaseDate: manifest.release_date,
  coverageStart: months[0],
  sourceCoverageStart: manifest.coverage_start,
  latestOfficialUrl: manifest.latest_official_url,
  generatedAt: manifest.generated_at,
  dataStatus: manifest.data_status,
  statusReason: manifest.status_reason,
  nextCheckDueAt: manifest.next_check_due_at,
  months,
  releaseDates: months.map((month) => releaseDates[month] ?? ''),
  cityIds: CITY_IDS,
  featuredCityIds: FEATURED_CITY_IDS,
  cityMap,
  series,
}
await mkdir(resolve(root, 'apps/miniprogram/data'), { recursive: true })
await writeFile(output, `// Generated by npm run miniprogram:data. Do not edit.\nmodule.exports=${JSON.stringify(snapshot)}\n`, 'utf8')
console.log(`Generated ${CITY_IDS.length} cities x ${monthLimit} months at ${output}`)
