import assert from 'node:assert/strict'
import { readFile, readdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import test from 'node:test'

const root = resolve(import.meta.dirname, '../..')
const discovery = await readFile(resolve(root, '.github/workflows/monthly-data-check.yml'), 'utf8')
const publisher = await readFile(resolve(root, '.github/workflows/monthly-data-auto-publish.yml'), 'utf8')
const recovery = await readFile(resolve(root, '.github/workflows/monthly-data-pending-publish.yml'), 'utf8')
const monitor = await readFile(resolve(root, '.github/workflows/monthly-data-post-publish-monitor.yml'), 'utf8')
const rehearsal = await readFile(resolve(root, '.github/workflows/cloud-write-rehearsal.yml'), 'utf8')
const fullReplay = await readFile(resolve(root, '.github/workflows/full-auto-update-replay.yml'), 'utf8')
const correctedPublisher = await readFile(resolve(root, '.github/workflows/manual-corrected-data-publish.yml'), 'utf8')
const historicalCorrection = await readFile(resolve(root, '.github/workflows/historical-data-correction.yml'), 'utf8')
const completeHistoryPublisher = await readFile(resolve(root, '.github/workflows/complete-history-data-publish.yml'), 'utf8')
const completeHistoryPreview = await readFile(resolve(root, '.github/workflows/miniprogram-15-year-preview.yml'), 'utf8')
const legacyMigration = await readFile(resolve(root, '.github/workflows/legacy-control-migration.yml'), 'utf8')
const manualRollback = await readFile(resolve(root, '.github/workflows/manual-data-rollback.yml'), 'utf8')
const pointerRepair = await readFile(resolve(root, 'scripts/miniprogram/repair-current-pointer.mjs'), 'utf8')
const genericPublisher = await readFile(resolve(root, 'scripts/miniprogram/publish-remote-data.mjs'), 'utf8')
const rollbackPublisher = await readFile(resolve(root, 'scripts/miniprogram/rollback-remote-data.mjs'), 'utf8')
const monitorSelector = await readFile(resolve(root, 'scripts/miniprogram/select-monitor-target.mjs'), 'utf8')
const monitorEventRegistration = await readFile(resolve(root, 'scripts/miniprogram/register-monitor-control-event.mjs'), 'utf8')
const strictValidatorDeployment = await readFile(resolve(root, 'scripts/miniprogram/deploy-strict-validator.mjs'), 'utf8')
const tencentCloudSdk = await readFile(resolve(root, 'scripts/miniprogram/tencent-cloud-sdk.mjs'), 'utf8')
const ci = await readFile(resolve(root, '.github/workflows/ci.yml'), 'utf8')

async function readWorkflowTree(directory) {
  const files = []
  const entries = await readdir(directory, { withFileTypes: true })
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name, 'en'))) {
    const absolutePath = resolve(directory, entry.name)
    if (entry.isDirectory()) files.push(...await readWorkflowTree(absolutePath))
    else if (entry.isFile() && /\.ya?ml$/i.test(entry.name)) files.push({ path: absolutePath, text: await readFile(absolutePath, 'utf8') })
  }
  return files
}

const allWorkflowFiles = await readWorkflowTree(resolve(root, '.github/workflows'))

test('recovery inputs accept only both empty or both set', () => {
  const validPair = (runId, runAttempt) => (!runId && !runAttempt) || (Boolean(runId) && Boolean(runAttempt))
  assert.equal(validPair('', ''), true)
  assert.equal(validPair('12345', '2'), true)
  assert.equal(validPair('12345', ''), false)
  assert.equal(validPair('', '2'), false)
})

test('discovery workflow remains read-only and has no production environment', () => {
  assert.match(discovery, /permissions:\s+contents: read/)
  assert.doesNotMatch(discovery, /contents: write|housing-data-production|TENCENTCLOUD_SECRET/)
})

test('publisher is triggered only by the named discovery workflow', () => {
  assert.match(publisher, /workflow_run:\s+workflows: \[monthly-data-check\]/)
  assert.doesNotMatch(publisher, /pull_request:|workflow_dispatch:/)
  assert.match(publisher, /workflow_run\.conclusion == 'success'/)
  assert.match(publisher, /needs\.inspect\.outputs\.update_available == 'true'/)
  assert.match(publisher, /Distinguish a verified update from a normal no-update check/)
  assert.match(publisher, /Require successful ordinary CI for the base commit/)
  assert.match(publisher, /actions\/workflows\/ci\.yml\/runs/)
})

test('discovery schedule concentrates checks around the official 09:30 release', () => {
  assert.match(discovery, /cron: "27,32,37,42,47,52,57 1 10-22 \* \*"/)
  assert.match(discovery, /cron: "2,7,12,17,22,27,30 2 10-22 \* \*"/)
  assert.match(discovery, /cron: "0 4,8 10-22 \* \*"/)
  assert.doesNotMatch(discovery, /7,37 0-9 10-22/)
})

test('a discovered update succeeds while genuine discovery anomalies fail', () => {
  assert.match(discovery, /2\)\s+echo "result=update_available"/)
  assert.match(discovery, /Official discovery failed with exit \$status/)
  assert.doesNotMatch(discovery, /continue-on-error: true/)
})

test('production pointer writes are serialized and never cancelled', () => {
  assert.match(publisher, /group: housing-data-production-publish/)
  assert.match(publisher, /cancel-in-progress: false/)
  assert.match(recovery, /group: housing-data-production-publish/)
  assert.match(recovery, /cancel-in-progress: false/)
  assert.match(monitor, /group: housing-data-production-publish/)
})

test('scheduled recovery reads state without credentials and publishes only a ready pending release', () => {
  const inspectAndRecover = recovery.slice(recovery.indexOf('  inspect:'), recovery.indexOf('  publish:'))
  const publish = recovery.slice(recovery.indexOf('  publish:'))
  assert.doesNotMatch(inspectAndRecover, /environment: housing-data-production|TENCENTCLOUD_SECRET/)
  assert.match(inspectAndRecover, /needs\.inspect\.outputs\.ready == 'true'/)
  assert.match(recovery, /vars\.AUTOMATIC_RELEASE_ENABLED == 'true'/)
  assert.match(inspectAndRecover, /miniprogram:data:verify-official-source/)
  assert.match(publish, /environment: housing-data-production/)
  assert.match(publish, /PRODUCTION_RELEASE_AUTHORIZED:/)
})

test('24-hour monitor uses a separate read-only identity and does not expose pointer writes', () => {
  assert.match(monitor, /workflow_dispatch:/)
  assert.match(monitor, /workflow_run:[\s\S]*monthly-data-auto-publish[\s\S]*monthly-data-pending-publish[\s\S]*manual-corrected-data-publish[\s\S]*historical-data-correction[\s\S]*complete-history-data-publish[\s\S]*manual-data-rollback/)
  assert.match(monitor, /select-monitor-target\.mjs/)
  assert.match(monitor, /release_audit_sha256/)
  assert.match(monitor, /revision_id/)
  assert.match(monitor, /control_event_sha256/)
  assert.match(monitor, /control_event_commit_sha/)
  assert.match(monitor, /control_event_run_id/)
  assert.match(monitor, /control_event_run_attempt/)
  assert.match(monitor, /TRIGGER_RUN_ATTEMPT: \$\{\{ github\.event\.workflow_run\.run_attempt \|\| '' \}\}/)
  assert.match(monitorSelector, /manual dataset version is invalid/)
  assert.match(monitorSelector, /\['rolled_back', 'automatically_rolled_back'\]/)
  assert.match(monitorSelector, /CORRECTION_FILE_PATTERN/)
  assert.match(monitorSelector, /github_run_id/)
  assert.match(monitorSelector, /release_type === 'historical_correction'/)
  assert.match(monitorSelector, /now - latestTransition\.occurredAt/)
  assert.match(monitorSelector, /latestTransition\.type === 'automatic_rollback'/)
  assert.match(monitorSelector, /latestTransition\.audit\.github_run_id/)
  assert.doesNotMatch(monitorSelector, /latest-auto-release/)
  assert.match(monitor, /TENCENTCLOUD_MONITOR_SECRET_ID/)
  assert.match(monitor, /monitor-remote-release\.mjs/)
  assert.match(monitor, /permissions:\s+contents: read/)
  assert.doesNotMatch(monitor, /contents: write|miniprogram:data:publish|storage', 'upload|TENCENTCLOUD_SECRET_ID:/)
  assert.doesNotMatch(monitorSelector, /TENCENTCLOUD_SECRET|putObject|uploadFile|git push/)
  assert.doesNotMatch(monitorEventRegistration, /TENCENTCLOUD_SECRET|putObject|uploadFile|git push/)
  const controlAuditCheck = monitor.indexOf('Verify the selected immutable control event audit identity')
  const releaseAuditCheck = monitor.indexOf('Verify the selected immutable release audit identity')
  const remoteCheck = monitor.indexOf('Verify cloud function, pointer, and all 70 remote shards')
  assert.ok(controlAuditCheck >= 0 && releaseAuditCheck > controlAuditCheck && remoteCheck > releaseAuditCheck)
  assert.match(monitor, /audit\.commit_sha !== process\.env\.EXPECTED_CONTROL_EVENT_COMMIT_SHA/)
  assert.match(monitor, /audit\.github_run_id/)
  assert.match(monitor, /manual-data-rollback-audit-v4/)
  assert.match(monitor, /audit\.finalizer_github_run_attempt/)
})

test('successful automatic rollback is registered without cloud credentials in every publishing workflow', () => {
  for (const workflow of [publisher, recovery, correctedPublisher, historicalCorrection, completeHistoryPublisher]) {
    assert.match(workflow, /Validate a successful automatic rollback for monitor registration/)
    assert.match(workflow, /register-monitor-control-event\.mjs/)
    assert.match(workflow, /Persist the automatic rollback monitor event without cloud credentials/)
    const registration = workflow.match(/- id: rollback_monitor_event[\s\S]*?git push origin "HEAD:\$\{DEFAULT_BRANCH\}"/)?.[0] || ''
    assert.match(registration, /if: failure\(\)/)
    assert.match(registration, /steps\.rollback_monitor_event\.outputs\.registered == 'true'/)
    assert.match(registration, /git add -- "\$EVENT_PATH" "\$FAILURE_PATH"/)
    assert.doesNotMatch(registration, /TENCENTCLOUD_(?:SECRET|MONITOR_SECRET)|PRODUCTION_RELEASE_AUTHORIZED/)
  }
  assert.match(monitorEventRegistration, /rollback_status === 'succeeded'/)
  assert.match(monitorEventRegistration, /failure\.commit_sha === expectedCommitSha/)
  assert.match(monitorEventRegistration, /eventSha256/)
})

test('remote monitor uses the official COS SDK with the read-only identity', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/monitor-remote-release.mjs'), 'utf8')
  assert.match(script, /cosCall\('headObject', 'housing-data\/current\.json'\)/)
  assert.match(script, /TENCENTCLOUD_MONITOR_SECRET_ID/)
  assert.doesNotMatch(script, /\['storage', '(?:detail|download)'/)
  assert.match(monitor, /Verify cloud function, pointer, and all 70 remote shards\s+env:\s+TENCENTCLOUD_MONITOR_SECRET_ID:/)
})

test('remote monitor invokes SCF directly without CloudBase CLI preflight permissions', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/monitor-remote-release.mjs'), 'utf8')
  assert.match(script, /scf\.Invoke\(/)
  assert.match(script, /Namespace: cloudEnvId/)
  assert.doesNotMatch(script, /runTcb|\['fn', 'invoke'/)
  assert.doesNotMatch(monitor, /tcb login/)
})

test('remote monitor separates immutable release integrity from bundled snapshot freshness', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/monitor-remote-release.mjs'), 'utf8')
  assert.match(script, /--integrity-only/)
  assert.match(script, /classifyRemoteFreshness/)
  assert.match(script, /integrityOnly \? null : require/)
  assert.match(script, /publish_audit_matched: true/)
  assert.match(script, /current-pointer-repair-/)
  assert.match(script, /legacy-control-migration-/)
  assert.match(script, /validateControlAuditTransitions/)
  assert.match(script, /validatePostWriteValidationReceiptInvocation/)
  assert.match(script, /cloud_function_verified: cloudFunctionVerified/)
  assert.doesNotMatch(script, /cloud_function_verified: true/)
  assert.match(script, /production_pointer_untouched: true/)
})

test('only the publish job receives the protected environment and credentials', () => {
  const prepare = publisher.slice(publisher.indexOf('  prepare:'), publisher.indexOf('  publish:'))
  const publish = publisher.slice(publisher.indexOf('  publish:'))
  assert.doesNotMatch(prepare, /environment: housing-data-production|TENCENTCLOUD_SECRET/)
  assert.match(publish, /environment: housing-data-production/)
  assert.match(publish, /needs\.inspect\.outputs\.repository_release_enabled == 'true'/)
  assert.match(publish, /PRODUCTION_RELEASE_AUTHORIZED:/)
  assert.match(publish, /secrets\.TENCENTCLOUD_SECRET_ID/)
  assert.match(publish, /CI_GATE_REPORT_SHA256/)
})

test('publisher workflows use direct SDK credentials without CloudBase CLI login', () => {
  assert.doesNotMatch(publisher, /tcb login/)
  assert.doesNotMatch(recovery, /tcb login/)
  assert.match(publisher, /Publish immutable release[\s\S]*TENCENTCLOUD_SECRET_ID:/)
  assert.match(recovery, /Retry guarded publication[\s\S]*TENCENTCLOUD_SECRET_ID:/)
})

test('manual write rehearsal is isolated from production keys', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/rehearse-cloud-write.mjs'), 'utf8')
  assert.match(rehearsal, /workflow_dispatch:/)
  assert.match(rehearsal, /environment: housing-data-production/)
  assert.match(rehearsal, /miniprogram:data:rehearse-write/)
  assert.doesNotMatch(rehearsal, /AUTOMATIC_RELEASE_ENABLED|tcb login/)
  assert.match(script, /housing-data\/rehearsals\/\$\{runId\}\//)
  assert.doesNotMatch(script, /putObject\(['"]housing-data\/(?:current\.json|releases\/)/)
  assert.match(script, /pointerKey = assertRehearsalKey\(`\$\{prefix\}current\.json`/)
  assert.match(script, /headObject/)
  assert.match(script, /getObject/)
  assert.match(script, /activatePointerWithRollback/)
  assert.match(script, /intentional isolated post-switch guard failure/)
  assert.match(script, /automatic_rollback_verified/)
  assert.match(script, /uploadedCityKeys\.length !== 70/)
  assert.match(script, /verify-remote-data\.mjs/)
})

test('full historical replay can write only below its numeric rehearsal prefix', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/replay-full-auto-update.ts'), 'utf8')
  assert.match(fullReplay, /workflow_dispatch:/)
  assert.match(fullReplay, /miniprogram:data:replay/)
  assert.match(fullReplay, /options:\s*\n\s*- "12"\s*\n\s*- "36"/)
  assert.match(fullReplay, /timeout-minutes: 300/)
  assert.match(fullReplay, /--months=\$\{\{ inputs\.months \}\}/)
  assert.doesNotMatch(fullReplay, /AUTOMATIC_RELEASE_ENABLED|tcb login/)
  assert.match(script, /housing-data\/rehearsals\/\$\{cloudRunId\}\/full-auto-update-year\//)
  assert.match(script, /assertRehearsalKey\(`/)
  assert.doesNotMatch(script, /putObject\([`'"]housing-data\/(?:current\.json|releases\/)/)
  assert.match(script, /production_pointer_untouched: true/)
  assert.match(script, /corrupt_candidate_rejected/)
  assert.match(script, /pointer_unchanged: true/)
  assert.match(script, /validateAuditReport\(auditReport, auditedBatches\)/)
  assert.match(script, /archive\.source_batch\.parser_version, PARSER_VERSION/)
  assert.match(script, /archive\.source_batch\.verification_method, FULL_RECORD_AUDIT_METHOD/)
  assert.match(script, /audit_version: FULL_RECORD_AUDIT_VERSION/)
  assert.match(script, /writeReplayCheckpoint\(replays, targetMonth\)/)
  assert.match(script, /requestedMonths >= 1 && requestedMonths <= 36/)
  assert.match(script, /for \(const \[index, targetMonth\] of targetMonths\.entries\(\)\)/)
})

test('manual corrected-data publication is narrowly locked behind both production switches', () => {
  assert.match(correctedPublisher, /workflow_dispatch:/)
  assert.match(correctedPublisher, /confirmation:/)
  assert.match(correctedPublisher, /test "\$CONFIRMATION" = "2026-06-4fd1d1a8ff12"/)
  assert.match(correctedPublisher, /Require successful ordinary CI for this exact commit/)
  assert.match(correctedPublisher, /environment: housing-data-production/)
  assert.match(correctedPublisher, /CI_EXPECTED_CURRENT_DATASET_VERSION: 2026-06-ec36ff8fb2e5/)
  assert.match(correctedPublisher, /CI_EXPECTED_CURRENT_SOURCE_DATASET_VERSION: 2026-06-679ea146d4e2/)
  assert.match(correctedPublisher, /data:audit/)
  assert.match(correctedPublisher, /verify-remote-data\.mjs/)
  const prepare = correctedPublisher.slice(correctedPublisher.indexOf('  prepare:'), correctedPublisher.indexOf('  publish:'))
  const publish = correctedPublisher.slice(correctedPublisher.indexOf('  publish:'))
  assert.match(prepare, /REPOSITORY_AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(prepare, /test "\$REPOSITORY_AUTOMATIC_RELEASE_ENABLED" = "true"/)
  assert.match(prepare, /OUTSIDE_ENV_PRODUCTION_AUTHORIZATION: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  assert.match(prepare, /workflow_id: '\.github\/workflows\/ci\.yml'/)
  assert.match(prepare, /(?:run|item)\.path === '\.github\/workflows\/ci\.yml'/)
  assert.doesNotMatch(prepare, /listWorkflowRunsForRepo|run\.name === 'ci'/)
  assert.match(publish, /AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(publish, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
})

test('complete-history publication accepts only the attested 180-month package behind both production switches', () => {
  assert.match(completeHistoryPublisher, /workflow_dispatch:/)
  assert.match(completeHistoryPublisher, /test "\$CONFIRMATION" = "2011-07-to-2026-06"/)
  assert.match(completeHistoryPublisher, /Require successful ordinary CI for this exact commit/)
  assert.match(completeHistoryPublisher, /environment: housing-data-production/)
  assert.match(completeHistoryPublisher, /miniprogram:data:stage-complete/)
  assert.match(completeHistoryPublisher, /miniprogram:data:verify-complete/)
  assert.match(completeHistoryPublisher, /miniprogram:data:publish-complete-history/)
  assert.match(completeHistoryPublisher, /CI_COMPLETE_SNAPSHOT_SHA256/)
  assert.match(completeHistoryPublisher, /AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(completeHistoryPublisher, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
})

test('15-year development preview is manually triggered and cannot touch production paths', async () => {
  const script = await readFile(resolve(root, 'scripts/miniprogram/publish-preview-complete-data.mjs'), 'utf8')
  assert.match(completeHistoryPreview, /workflow_dispatch:/)
  assert.match(completeHistoryPreview, /miniprogram:cloud:deploy-preview/)
  assert.match(completeHistoryPreview, /miniprogram:data:publish-preview/)
  assert.doesNotMatch(completeHistoryPreview, /AUTOMATIC_RELEASE_ENABLED|PRODUCTION_RELEASE_AUTHORIZED/)
  assert.match(script, /dataRoot = 'housing-data\/preview'/)
  assert.match(script, /production_pointer_untouched: true/)
  assert.match(script, /production_release_prefix_untouched: true/)
  assert.doesNotMatch(script, /housing-data\/current\.json|housing-data\/releases\//)
})

test('legacy current pointer repair is fail-closed under control schema v1', () => {
  assert.match(pointerRepair, /Direct current\.json repair is disabled under control schema v1/)
  assert.doesNotMatch(pointerRepair, /uploadFile|putObject|housing-data\/current\.json/)
})

test('ordinary publish and rollback cannot infer revocations from an active legacy pointer', () => {
  assert.match(genericPublisher, /assertProductionPointerBaseline\(previous\)/)
  assert.match(rollbackPublisher, /assertProductionPointerBaseline\(current\)/)
  assert.doesNotMatch(rollbackPublisher, /Legacy active revision manifest|revokedSourceDatasetVersions = \[\]/)
})

test('production publish and rollback scripts have no local interactive write bypass', () => {
  assert.match(genericPublisher, /if \(!dryRun && !ciMode\).*authorized GitHub Actions workflow/)
  assert.match(genericPublisher, /const ciGate = dryRun \? null : await authorizeCiRelease/)
  assert.doesNotMatch(genericPublisher, /createInterface|stdin\.isTTY|prompt\.question/)
  const authorize = rollbackPublisher.indexOf('await authorizeCiRollback')
  const cloudClient = rollbackPublisher.indexOf('createTencentCloudClient({ cloudEnvId })')
  assert.ok(authorize >= 0 && cloudClient > authorize)
  assert.doesNotMatch(rollbackPublisher, /createInterface|stdin\.isTTY|prompt\.question/)
  assert.match(rollbackPublisher, /immutable-audit/)
  assert.match(rollbackPublisher, /validateManualRollbackAudit/)
})

test('automatic and manual rollback revoke both package and source identities atomically', () => {
  assert.match(genericPublisher, /appendFailedReleaseRevocations/)
  assert.match(genericPublisher, /sourceDatasetVersion: manifest\.source_dataset_version/)
  assert.match(rollbackPublisher, /appendFailedReleaseRevocations/)
  assert.match(rollbackPublisher, /sourceDatasetVersion: baseline\.current\.source_dataset_version/)
  assert.doesNotMatch(rollbackPublisher, /appendFailedDatasetRevocation/)
})

test('manual rollback is protected, exact, read-only to the repository, and audited separately', () => {
  assert.match(manualRollback, /workflow_dispatch:/)
  assert.doesNotMatch(manualRollback, /schedule:|workflow_run:/)
  assert.match(manualRollback, /group: housing-data-production-publish/)
  assert.match(manualRollback, /cancel-in-progress: false/)
  const prepare = manualRollback.slice(manualRollback.indexOf('  prepare:'), manualRollback.indexOf('  rollback:'))
  const rollback = manualRollback.slice(manualRollback.indexOf('  rollback:'), manualRollback.indexOf('  audit:'))
  const audit = manualRollback.slice(manualRollback.indexOf('  audit:'))
  assert.doesNotMatch(prepare, /environment: housing-data-production|TENCENTCLOUD_SECRET/)
  assert.match(prepare, /test "\$CONFIRMATION" = "\$DATASET_VERSION"/)
  assert.match(prepare, /test "\$REPOSITORY_AUTOMATIC_RELEASE_ENABLED" = "true"/)
  assert.match(prepare, /test -z "\$OUTSIDE_ENV_PRODUCTION_AUTHORIZATION" \|\| test "\$OUTSIDE_ENV_PRODUCTION_AUTHORIZATION" = "false"/)
  assert.match(prepare, /workflow_id: '\.github\/workflows\/ci\.yml'/)
  assert.match(prepare, /(?:run|item)\.path === '\.github\/workflows\/ci\.yml'/)
  assert.doesNotMatch(prepare, /listWorkflowRunsForRepo|run\.name === 'ci'/)
  assert.match(prepare, /inputs\.recovery_run_id/)
  assert.match(prepare, /inputs\.recovery_run_attempt/)
  assert.match(prepare, /if \[\[ -n "\$RECOVERY_RUN_ID" \|\| -n "\$RECOVERY_RUN_ATTEMPT" \]\]; then[\s\S]*test -n "\$RECOVERY_RUN_ID"[\s\S]*test -n "\$RECOVERY_RUN_ATTEMPT"[\s\S]*fi/)
  assert.doesNotMatch(prepare, /test -z "\$RECOVERY_RUN_ID" && test -z "\$RECOVERY_RUN_ATTEMPT" \|\| test -n/)
  assert.match(prepare, /actions\.getWorkflowRunAttempt/)
  assert.match(prepare, /artifact_source_run_attempt/)
  assert.match(prepare, /run\.path !== '\.github\/workflows\/manual-data-rollback\.yml'/)
  assert.match(prepare, /reusable_audit=true/)
  assert.match(prepare, /Verify the reusable audit finalizer ordinary CI run/)
  assert.match(prepare, /finalizer_ordinary_ci_run_id/)
  assert.match(rollback, /environment: housing-data-production/)
  assert.match(rollback, /permissions:\s+actions: read\s+contents: read/)
  assert.doesNotMatch(rollback, /contents: write|git push/)
  assert.match(rollback, /TENCENTCLOUD_SECRET_ID:/)
  assert.match(rollback, /ROLLBACK_CONFIRMATION: \$\{\{ inputs\.confirmation \}\}/)
  assert.match(rollback, /AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(rollback, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  assert.match(rollback, /CI_ORDINARY_CI_WORKFLOW: \.github\/workflows\/ci\.yml/)
  const persistIntent = rollback.indexOf('Persist the immutable intent before any production object write')
  const finalBranchCheck = rollback.indexOf('Reconfirm the default branch immediately before the production switch')
  const applyIntent = rollback.indexOf('Apply the durable intent or finalize it read-only after an interrupted switch')
  assert.ok(persistIntent >= 0 && finalBranchCheck > persistIntent && applyIntent > finalBranchCheck)
  assert.match(rollback, /manual-data-rollback-intent-\$\{\{ github\.run_id \}\}-\$\{\{ github\.run_attempt \}\}/)
  assert.match(rollback, /--origin-run-attempt=\$\{\{ steps\.intent\.outputs\.origin_run_attempt \}\}/)
  assert.match(rollback, /--apply-intent=\$\{\{ steps\.intent\.outputs\.intent_path \}\}/)
  assert.match(audit, /permissions:\s+actions: read\s+contents: write/)
  assert.doesNotMatch(audit, /TENCENTCLOUD_(?:SECRET|MONITOR_SECRET)/)
  assert.match(audit, /persist-credentials: false/)
  assert.match(audit, /validateManualRollbackAudit/)
  assert.match(audit, /expectedFinalizerGithubRunAttempt/)
  assert.match(audit, /expectedFinalizerOrdinaryCiRunId/)
  assert.match(audit, /GITHUB_TOKEN: \$\{\{ github\.token \}\}/)
})

test('legacy control migration is one-time, protected, exact, and never enables automatic release', async () => {
  assert.match(legacyMigration, /workflow_dispatch:/)
  assert.doesNotMatch(legacyMigration, /schedule:|workflow_run:/)
  assert.match(legacyMigration, /test "\$CONFIRMATION" = "legacy-control-2026-06-e9788d0bddf3"/)
  assert.match(legacyMigration, /recovery_run_id:/)
  assert.match(legacyMigration, /recovery_run_attempt:/)
  assert.match(legacyMigration, /test "\$REPOSITORY_AUTOMATIC_RELEASE_ENABLED" = "false"/)
  assert.match(legacyMigration, /OUTSIDE_ENV_PRODUCTION_AUTHORIZATION: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  assert.match(legacyMigration, /test -z "\$OUTSIDE_ENV_PRODUCTION_AUTHORIZATION" \|\| test "\$OUTSIDE_ENV_PRODUCTION_AUTHORIZATION" = "false"/)
  assert.doesNotMatch(legacyMigration, /vars\.LEGACY_CONTROL_MIGRATION_AUTHORIZED/)
  assert.equal((legacyMigration.match(/echo "LEGACY_CONTROL_MIGRATION_AUTHORIZED=true" >> "\$GITHUB_ENV"/g) || []).length, 1)
  assert.match(legacyMigration, /Require successful ordinary CI for this exact commit/)
  assert.match(legacyMigration, /actions\.listWorkflowRuns/)
  assert.match(legacyMigration, /workflow_id: '\.github\/workflows\/ci\.yml'/)
  assert.doesNotMatch(legacyMigration, /listWorkflowRunsForRepo|run\.name === 'ci'/)
  assert.match(legacyMigration, /actions\.getWorkflowRunAttempt/)
  assert.match(legacyMigration, /run\.path !== '\.github\/workflows\/legacy-control-migration\.yml'/)
  const prepare = legacyMigration.slice(legacyMigration.indexOf('  prepare:'), legacyMigration.indexOf('  migrate:'))
  const migrate = legacyMigration.slice(legacyMigration.indexOf('  migrate:'), legacyMigration.indexOf('  audit:'))
  const audit = legacyMigration.slice(legacyMigration.indexOf('  audit:'))
  assert.doesNotMatch(prepare, /environment: housing-data-production|TENCENTCLOUD_SECRET/)
  assert.doesNotMatch(prepare, /data:audit|data\/audit-report\.json|data\/raw|apps\/miniprogram\/data\/snapshot\.js/)
  assert.match(prepare, /fixed evidence and deterministic migration candidate/)
  assert.match(prepare, /if \[\[ -n "\$RECOVERY_RUN_ID" \|\| -n "\$RECOVERY_RUN_ATTEMPT" \]\]; then[\s\S]*test -n "\$RECOVERY_RUN_ID"[\s\S]*test -n "\$RECOVERY_RUN_ATTEMPT"[\s\S]*fi/)
  assert.match(prepare, /- id: recovery\s+name: Bind a requested recovery intent/)
  assert.match(prepare, /base: run\.head_sha,[\s\S]*head: context\.sha,[\s\S]*\)\.data\.status/)
  assert.match(prepare, /\['identical', 'ahead'\]/)
  assert.match(prepare, /RECOVERY_ORIGIN_COMMIT_SHA: \$\{\{ steps\.recovery\.outputs\.origin_commit_sha \}\}/)
  assert.match(migrate, /environment: housing-data-production/)
  assert.match(migrate, /permissions:\s+actions: read\s+contents: read/)
  assert.doesNotMatch(migrate, /contents: write|git push/)
  const environmentGate = migrate.indexOf('test "$AUTOMATIC_RELEASE_ENABLED" = "false"')
  const jobScopedAuthorization = migrate.indexOf('echo "LEGACY_CONTROL_MIGRATION_AUTHORIZED=true" >> "$GITHUB_ENV"')
  const intentUpload = migrate.indexOf('Persist the immutable intent before any production object write')
  const intentVerification = migrate.indexOf('--verify-intent="$intent_path"')
  const intentApply = migrate.indexOf('Apply the immutable intent or recheck an interrupted pointer switch')
  const strictDeploy = migrate.indexOf('Deploy the strict manifest function only after the pointer switch')
  const strictFinalize = migrate.indexOf('Finalize the migrated pointer with the deployed strict validator')
  assert.ok(environmentGate >= 0 && intentVerification > environmentGate)
  assert.ok(intentUpload > intentVerification && jobScopedAuthorization > intentUpload && intentApply > jobScopedAuthorization)
  assert.ok(strictDeploy > intentApply && strictFinalize > strictDeploy)
  assert.doesNotMatch(migrate.slice(0, jobScopedAuthorization), /LEGACY_CONTROL_MIGRATION_AUTHORIZED=true/)
  assert.match(migrate, /legacy-control-migration-intent-\$\{\{ needs\.prepare\.outputs\.origin_run_id \}\}-\$\{\{ needs\.prepare\.outputs\.origin_run_attempt \}\}/)
  assert.match(migrate, /run-id: \$\{\{ needs\.prepare\.outputs\.origin_run_id \}\}/)
  assert.match(migrate, /github-token: \$\{\{ github\.token \}\}/)
  assert.match(migrate, /retention-days: 90/)
  assert.match(migrate, /--migration=legacy-control-2026-06-e9788d0bddf3/)
  assert.match(migrate, /--confirmation="\$CONFIRMATION"/)
  assert.match(migrate, /--prepare-intent/)
  assert.match(migrate, /--verify-intent="\$intent_path"/)
  assert.match(migrate, /--apply-intent="\$\{\{ steps\.intent\.outputs\.intent_path \}\}"/)
  assert.match(migrate, /--origin-run-id="\$ORIGIN_RUN_ID"/)
  assert.match(migrate, /--origin-run-attempt="\$ORIGIN_RUN_ATTEMPT"/)
  assert.match(migrate, /ORIGIN_COMMIT_SHA: \$\{\{ needs\.prepare\.outputs\.origin_commit_sha \}\}/)
  assert.match(migrate, /--apply/)
  assert.match(migrate, /source_files=\(audited-legacy-migrations\.js index\.js package\.json validate-current\.js validation-receipt\.js\)/)
  assert.match(migrate, /zip -X -q getHousingDataManifest\.zip/)
  assert.match(migrate, /node scripts\/miniprogram\/deploy-strict-validator\.mjs/)
  assert.doesNotMatch(migrate, /tcb (?:login|fn deploy|logout)/)
  assert.match(migrate, /--finalize-intent="\$\{\{ steps\.intent\.outputs\.intent_path \}\}"/)
  const finalizationStep = migrate.slice(
    migrate.indexOf('Finalize the migrated pointer with the deployed strict validator'),
    migrate.indexOf('Recheck the migrated pointer, cloud function, registry, and all 70 cities read-only'),
  )
  assert.match(finalizationStep, /TENCENTCLOUD_SECRET_ID: \$\{\{ secrets\.TENCENTCLOUD_MONITOR_SECRET_ID \}\}/)
  assert.match(finalizationStep, /TENCENTCLOUD_SECRET_KEY: \$\{\{ secrets\.TENCENTCLOUD_MONITOR_SECRET_KEY \}\}/)
  assert.doesNotMatch(finalizationStep, /secrets\.TENCENTCLOUD_SECRET_(?:ID|KEY)/)
  assert.match(migrate, /monitor-remote-release\.mjs[\s\S]*--integrity-only/)
  assert.match(migrate, /AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(migrate, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  assert.match(migrate, /test -z "\$PRODUCTION_RELEASE_AUTHORIZED" \|\| test "\$PRODUCTION_RELEASE_AUTHORIZED" = "false"/)
  assert.match(migrate, /--migration-audit-dir=work\/control-migrations\/legacy-control-2026-06-e9788d0bddf3\/immutable-audit/)
  assert.match(audit, /permissions:\s+actions: read\s+contents: write/)
  assert.doesNotMatch(audit, /TENCENTCLOUD_(?:SECRET|MONITOR_SECRET)/)
  assert.match(audit, /persist-credentials: false/)
  assert.match(audit, /GITHUB_TOKEN: \$\{\{ github\.token \}\}/)
  assert.match(audit, /ref: \$\{\{ needs\.prepare\.outputs\.commit_sha \}\}/)
  assert.match(audit, /origin\/\$DEFAULT_BRANCH/)
  assert.match(audit, /ORIGIN_COMMIT_SHA: \$\{\{ needs\.prepare\.outputs\.origin_commit_sha \}\}/)
  assert.match(audit, /expectedCommitSha: process\.env\.ORIGIN_COMMIT_SHA/)
  assert.match(audit, /expectedOriginGithubRunId: process\.env\.ORIGIN_RUN_ID/)
  assert.match(audit, /expectedOriginGithubRunAttempt: process\.env\.ORIGIN_RUN_ATTEMPT/)
  assert.match(audit, /expectedFinalizerGithubRunId: process\.env\.FINALIZER_RUN_ID/)
  assert.match(audit, /expectedFinalizerGithubRunAttempt: process\.env\.FINALIZER_RUN_ATTEMPT/)
  assert.doesNotMatch(audit, /merge-base --is-ancestor|\[skip ci\]/)
  assert.equal((legacyMigration.match(/persist-credentials: false/g) || []).length, 3)
  assert.doesNotMatch(legacyMigration, /PRODUCTION_RELEASE_AUTHORIZED[^\n]*true|AUTOMATIC_RELEASE_ENABLED[^\n]*true/)

  assert.match(tencentCloudSdk, /FunctionName: functionName/)
  assert.match(tencentCloudSdk, /Namespace: cloudEnvId/)
  assert.match(tencentCloudSdk, /InstallDependency: 'TRUE'/)
  assert.match(tencentCloudSdk, /Publish: 'FALSE'/)
  assert.match(strictValidatorDeployment, /updateFunctionCode\(\{ functionName, zipFile \}\)/)
  assert.match(strictValidatorDeployment, /LEGACY_CONTROL_MIGRATION_AUTHORIZED !== 'true'/)
  assert.match(strictValidatorDeployment, /AUTOMATIC_RELEASE_ENABLED !== 'false'/)
  assert.match(strictValidatorDeployment, /Production release authorization must remain false or unset/)

  const migrationScript = await readFile(resolve(root, 'scripts/miniprogram/migrate-legacy-control.mjs'), 'utf8')
  const validatorPreflight = migrationScript.indexOf("invokeFunction('getHousingDataManifest', { action: 'describe_validator' })")
  const intentParser = migrationScript.indexOf('parseMigrationIntentText(preparedIntentText')
  const finalizeBranch = migrationScript.slice(migrationScript.indexOf('async function finalizePreparedIntent'))
  const applyBranch = migrationScript.slice(migrationScript.indexOf('async function applyPreparedIntent'))
  const recoveryBranch = migrationScript.slice(
    migrationScript.indexOf('async function verifyAppliedPointer'),
    migrationScript.indexOf('async function finalizePreparedIntent'),
  )
  const firstProductionWrite = applyBranch.indexOf('await cloud.putObject(')
  assert.ok(validatorPreflight >= 0 && finalizeBranch.indexOf("invokeFunction('getHousingDataManifest', { action: 'describe_validator' })") >= 0)
  assert.ok(intentParser >= 0 && firstProductionWrite > 0)
  assert.doesNotMatch(applyBranch, /describe_validator/)
  assert.doesNotMatch(recoveryBranch, /putObject/)
  assert.match(migrationScript, /confirmation !== descriptor\.migration_id/)
  assert.match(migrationScript, /PRODUCTION_RELEASE_AUTHORIZED must remain false or unset/)
  assert.match(migrationScript, /String\(process\.env\.GITHUB_RUN_ATTEMPT\) !== intent\.github_run_attempt/)
  assert.match(migrationScript, /A new GitHub run or attempt may recover an applied intent but may not execute its production writes/)
  assert.doesNotMatch(migrationScript, /writeFile\(resolve\(root, 'data\/releases'/)
})

test('generic historical correction requires a reviewed request, full audit, protected environment, and immutable evidence', () => {
  assert.match(historicalCorrection, /workflow_dispatch:/)
  assert.match(historicalCorrection, /data\/corrections\//)
  assert.match(historicalCorrection, /revision_id_confirmation/)
  assert.match(historicalCorrection, /Require successful ordinary CI for this exact commit/)
  assert.match(historicalCorrection, /data:audit/)
  assert.match(historicalCorrection, /miniprogram:data:prepare-historical-correction/)
  assert.match(historicalCorrection, /environment: housing-data-production/)
  assert.match(historicalCorrection, /CI_SUPERSEDES_SOURCE_DATASET_VERSION/)
  assert.match(historicalCorrection, /Persist immutable publication and revocation audits/)
  const prepare = historicalCorrection.slice(historicalCorrection.indexOf('  prepare:'), historicalCorrection.indexOf('  publish:'))
  const publish = historicalCorrection.slice(historicalCorrection.indexOf('  publish:'))
  assert.match(prepare, /REPOSITORY_AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(prepare, /OUTSIDE_ENV_PRODUCTION_AUTHORIZATION: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  assert.match(prepare, /workflow_id: '\.github\/workflows\/ci\.yml'/)
  assert.match(prepare, /(?:run|item)\.path === '\.github\/workflows\/ci\.yml'/)
  assert.doesNotMatch(prepare, /listWorkflowRunsForRepo|run\.name === 'ci'/)
  assert.match(publish, /AUTOMATIC_RELEASE_ENABLED: \$\{\{ vars\.AUTOMATIC_RELEASE_ENABLED \}\}/)
  assert.match(publish, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
})

test('all external workflow actions are pinned to immutable 40-character commits', () => {
  assert.ok(allWorkflowFiles.length > 0)
  for (const workflow of allWorkflowFiles) {
    const uses = [...workflow.text.matchAll(/uses:\s*([^\s#]+)/g)].map((match) => match[1])
    for (const value of uses) {
      if (value.startsWith('./')) continue
      assert.match(value, /^[a-z0-9_.-]+\/[a-z0-9_.-]+@[a-f0-9]{40}$/i, `mutable action reference in ${workflow.path}: ${value}`)
    }
  }
})

test('untrusted pending URLs are validated and passed as quoted environment arguments', () => {
  assert.match(recovery, /node scripts\/miniprogram\/inspect-pending-release\.mjs/)
  assert.match(recovery, /OFFICIAL_URL: \$\{\{ needs\.inspect\.outputs\.official_url \}\}/)
  assert.match(recovery, /"--url=\$OFFICIAL_URL"/)
  assert.doesNotMatch(recovery, /--url=\$\{\{ needs\.inspect\.outputs\.official_url \}\}/)
})

test('repository and production-environment release authorization are independent fail-closed gates', () => {
  for (const workflow of [publisher, recovery, correctedPublisher, historicalCorrection, manualRollback]) {
    assert.match(workflow, /OUTSIDE_ENV_PRODUCTION_AUTHORIZATION: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
    assert.match(workflow, /test -z "\$OUTSIDE_ENV_PRODUCTION_AUTHORIZATION"/)
    assert.match(workflow, /PRODUCTION_RELEASE_AUTHORIZED: \$\{\{ vars\.PRODUCTION_RELEASE_AUTHORIZED \}\}/)
  }
})

test('recovery verifies same-commit ordinary CI before the production environment job', () => {
  const recover = recovery.slice(recovery.indexOf('  recover:'), recovery.indexOf('  publish:'))
  assert.match(recover, /actions\/workflows\/ci\.yml\/runs/)
  assert.match(recover, /ordinary-ci-evidence\.json/)
  assert.match(recover, /CI_EVIDENCE_RUN_ID:/)
  assert.doesNotMatch(recover, /environment: housing-data-production|TENCENTCLOUD_SECRET/)
  assert.match(recovery.slice(recovery.indexOf('  publish:')), /housing-data-recovery-candidate-/)
})

test('public workflow artifacts never upload the private audit directory', () => {
  assert.doesNotMatch(recovery, /^\s+work\/private-audit\//m)
  assert.match(recovery, /private-audit-reference\.json|work\/auto-release\//)
})

test('workflow tokens use read-only defaults and write only in jobs that push', () => {
  assert.match(ci, /permissions:\s+contents: read/)
  assert.match(publisher, /permissions:\s+actions: read\s+contents: read/)
  assert.match(correctedPublisher, /permissions:\s+actions: read\s+contents: read/)
  assert.match(historicalCorrection, /permissions:\s+actions: read\s+contents: read/)
  assert.match(correctedPublisher.slice(correctedPublisher.indexOf('  publish:')), /permissions:\s+actions: read\s+contents: write/)
  assert.match(historicalCorrection.slice(historicalCorrection.indexOf('  publish:')), /permissions:\s+actions: read\s+contents: write/)
  const rollbackJob = manualRollback.slice(manualRollback.indexOf('  rollback:'), manualRollback.indexOf('  audit:'))
  const rollbackAudit = manualRollback.slice(manualRollback.indexOf('  audit:'))
  assert.match(rollbackJob, /permissions:\s+actions: read\s+contents: read/)
  assert.doesNotMatch(rollbackJob, /contents: write/)
  assert.match(rollbackAudit, /permissions:\s+actions: read\s+contents: write/)
  assert.doesNotMatch(rollbackAudit, /TENCENTCLOUD_(?:SECRET|MONITOR_SECRET)/)
  const legacyMigrate = legacyMigration.slice(legacyMigration.indexOf('  migrate:'), legacyMigration.indexOf('  audit:'))
  const legacyAudit = legacyMigration.slice(legacyMigration.indexOf('  audit:'))
  assert.match(legacyMigrate, /permissions:\s+actions: read\s+contents: read/)
  assert.doesNotMatch(legacyMigrate, /contents: write/)
  assert.match(legacyAudit, /permissions:\s+actions: read\s+contents: write/)
  assert.doesNotMatch(legacyAudit, /TENCENTCLOUD_(?:SECRET|MONITOR_SECRET)/)
})

test('manual secret-bearing jobs reject non-default refs in repository code', () => {
  for (const workflow of [rehearsal, fullReplay]) {
    assert.match(workflow, /if: github\.ref == format\('refs\/heads\/\{0\}', github\.event\.repository\.default_branch\)/)
    assert.match(workflow, /persist-credentials: false/)
    assert.match(workflow, /origin\/\$DEFAULT_BRANCH/)
  }
  assert.match(monitor, /needs\.inspect\.outputs\.active == 'true' && github\.ref == format/)
})
